package com.sandrew.mybatis.model;

import java.util.Date;

import org.apache.ibatis.annotations.ColumnName;
import org.apache.ibatis.annotations.TableName;

@TableName("TM_USER")
public class TmUserPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.USER_ID
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
	@ColumnName("USER_ID")
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.USER_CODE
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
	@ColumnName("USER_CODE")
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.USER_NAME
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.PASSWORD
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.SEX
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.PHONE
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.MOBILE
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.EMAIL
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.BIRTHDAY
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.USER_TYPE
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.USER_STATUS
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    private Integer userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.CREATE_DATE
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.CREATE_BY
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.UPDATE_DATE
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.UPDATE_BY
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    private Integer updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.USER_ID
     *
     * @return the value of tm_user.USER_ID
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.USER_ID
     *
     * @param userId the value for tm_user.USER_ID
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.USER_CODE
     *
     * @return the value of tm_user.USER_CODE
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.USER_CODE
     *
     * @param userCode the value for tm_user.USER_CODE
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.USER_NAME
     *
     * @return the value of tm_user.USER_NAME
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.USER_NAME
     *
     * @param userName the value for tm_user.USER_NAME
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.PASSWORD
     *
     * @return the value of tm_user.PASSWORD
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.PASSWORD
     *
     * @param password the value for tm_user.PASSWORD
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.SEX
     *
     * @return the value of tm_user.SEX
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.SEX
     *
     * @param sex the value for tm_user.SEX
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.PHONE
     *
     * @return the value of tm_user.PHONE
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.PHONE
     *
     * @param phone the value for tm_user.PHONE
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.MOBILE
     *
     * @return the value of tm_user.MOBILE
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.MOBILE
     *
     * @param mobile the value for tm_user.MOBILE
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.EMAIL
     *
     * @return the value of tm_user.EMAIL
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.EMAIL
     *
     * @param email the value for tm_user.EMAIL
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.BIRTHDAY
     *
     * @return the value of tm_user.BIRTHDAY
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.BIRTHDAY
     *
     * @param birthday the value for tm_user.BIRTHDAY
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.USER_TYPE
     *
     * @return the value of tm_user.USER_TYPE
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.USER_TYPE
     *
     * @param userType the value for tm_user.USER_TYPE
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.USER_STATUS
     *
     * @return the value of tm_user.USER_STATUS
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.USER_STATUS
     *
     * @param userStatus the value for tm_user.USER_STATUS
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.CREATE_DATE
     *
     * @return the value of tm_user.CREATE_DATE
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.CREATE_DATE
     *
     * @param createDate the value for tm_user.CREATE_DATE
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.CREATE_BY
     *
     * @return the value of tm_user.CREATE_BY
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.CREATE_BY
     *
     * @param createBy the value for tm_user.CREATE_BY
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.UPDATE_DATE
     *
     * @return the value of tm_user.UPDATE_DATE
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.UPDATE_DATE
     *
     * @param updateDate the value for tm_user.UPDATE_DATE
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.UPDATE_BY
     *
     * @return the value of tm_user.UPDATE_BY
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.UPDATE_BY
     *
     * @param updateBy the value for tm_user.UPDATE_BY
     *
     * @mbggenerated Fri Apr 08 21:56:42 CST 2016
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }
}