package com.sandrew.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class TrUserRolePO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_user_role.ID
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_user_role.USER_ID
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_user_role.ROLE_ID
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_user_role.CREATE_BY
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_user_role.CREATE_DATE
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_user_role.UPDATE_BY
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    private Integer updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_user_role.UPDATE_DATE
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_user_role.ID
     *
     * @return the value of tr_user_role.ID
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_user_role.ID
     *
     * @param id the value for tr_user_role.ID
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_user_role.USER_ID
     *
     * @return the value of tr_user_role.USER_ID
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_user_role.USER_ID
     *
     * @param userId the value for tr_user_role.USER_ID
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_user_role.ROLE_ID
     *
     * @return the value of tr_user_role.ROLE_ID
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_user_role.ROLE_ID
     *
     * @param roleId the value for tr_user_role.ROLE_ID
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_user_role.CREATE_BY
     *
     * @return the value of tr_user_role.CREATE_BY
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_user_role.CREATE_BY
     *
     * @param createBy the value for tr_user_role.CREATE_BY
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_user_role.CREATE_DATE
     *
     * @return the value of tr_user_role.CREATE_DATE
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_user_role.CREATE_DATE
     *
     * @param createDate the value for tr_user_role.CREATE_DATE
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_user_role.UPDATE_BY
     *
     * @return the value of tr_user_role.UPDATE_BY
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_user_role.UPDATE_BY
     *
     * @param updateBy the value for tr_user_role.UPDATE_BY
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_user_role.UPDATE_DATE
     *
     * @return the value of tr_user_role.UPDATE_DATE
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_user_role.UPDATE_DATE
     *
     * @param updateDate the value for tr_user_role.UPDATE_DATE
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}