package com.sandrew.mybatis.mapper;

import com.sandrew.mybatis.model.TmFunctionPO;

public interface TmFunctionPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_function
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    int deleteByPrimaryKey(Integer functionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_function
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    int insert(TmFunctionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_function
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    int insertSelective(TmFunctionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_function
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    TmFunctionPO selectByPrimaryKey(Integer functionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_function
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    int updateByPrimaryKeySelective(TmFunctionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_function
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    int updateByPrimaryKey(TmFunctionPO record);
}