package com.sandrew.mybatis.mapper;

import com.sandrew.mybatis.model.TrUserRolePO;

public interface TrUserRolePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    int insert(TrUserRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    int insertSelective(TrUserRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    TrUserRolePO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    int updateByPrimaryKeySelective(TrUserRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    int updateByPrimaryKey(TrUserRolePO record);
}