package com.sandrew.mybatis.mapper;

import com.sandrew.mybatis.model.TmRolePO;

public interface TmRolePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    int insert(TmRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    int insertSelective(TmRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    TmRolePO selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    int updateByPrimaryKeySelective(TmRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    int updateByPrimaryKey(TmRolePO record);
}