package com.sandrew.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class TmRolePO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_role.ROLE_ID
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_role.ROLE_CODE
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_role.ROLE_NAME
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_role.ROLE_TYPE
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    private Integer roleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_role.ROLE_STATUS
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    private Integer roleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_role.CREATE_BY
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_role.CREATE_DATE
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_role.UPDATE_BY
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    private Integer updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_role.UPDATE_DATE
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_role.ROLE_ID
     *
     * @return the value of tm_role.ROLE_ID
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_role.ROLE_ID
     *
     * @param roleId the value for tm_role.ROLE_ID
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_role.ROLE_CODE
     *
     * @return the value of tm_role.ROLE_CODE
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_role.ROLE_CODE
     *
     * @param roleCode the value for tm_role.ROLE_CODE
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_role.ROLE_NAME
     *
     * @return the value of tm_role.ROLE_NAME
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_role.ROLE_NAME
     *
     * @param roleName the value for tm_role.ROLE_NAME
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_role.ROLE_TYPE
     *
     * @return the value of tm_role.ROLE_TYPE
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public Integer getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_role.ROLE_TYPE
     *
     * @param roleType the value for tm_role.ROLE_TYPE
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public void setRoleType(Integer roleType) {
        this.roleType = roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_role.ROLE_STATUS
     *
     * @return the value of tm_role.ROLE_STATUS
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public Integer getRoleStatus() {
        return roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_role.ROLE_STATUS
     *
     * @param roleStatus the value for tm_role.ROLE_STATUS
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public void setRoleStatus(Integer roleStatus) {
        this.roleStatus = roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_role.CREATE_BY
     *
     * @return the value of tm_role.CREATE_BY
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_role.CREATE_BY
     *
     * @param createBy the value for tm_role.CREATE_BY
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_role.CREATE_DATE
     *
     * @return the value of tm_role.CREATE_DATE
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_role.CREATE_DATE
     *
     * @param createDate the value for tm_role.CREATE_DATE
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_role.UPDATE_BY
     *
     * @return the value of tm_role.UPDATE_BY
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_role.UPDATE_BY
     *
     * @param updateBy the value for tm_role.UPDATE_BY
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_role.UPDATE_DATE
     *
     * @return the value of tm_role.UPDATE_DATE
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_role.UPDATE_DATE
     *
     * @param updateDate the value for tm_role.UPDATE_DATE
     *
     * @mbggenerated Sat Apr 16 13:49:44 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}